#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)

# Ensure user library path is available for package loading
lib_dir <- Sys.getenv("R_LIBS_USER", unset = "/workspace/.Rlibs")
dir.create(lib_dir, recursive = TRUE, showWarnings = FALSE)
.libPaths(c(lib_dir, .libPaths()))

parse_args <- function(argsv) {
  kv <- list()
  i <- 1
  while (i <= length(argsv)) {
    key <- argsv[i]
    if (startsWith(key, "--")) {
      key <- substring(key, 3)
      if ((i + 1) <= length(argsv) && !startsWith(argsv[i + 1], "--")) {
        kv[[key]] <- argsv[i + 1]
        i <- i + 2
      } else {
        kv[[key]] <- TRUE
        i <- i + 1
      }
    } else {
      i <- i + 1
    }
  }
  kv
}

argv <- parse_args(args)
if (is.null(argv$year) || is.null(argv$pdf)) {
  stop("Usage: Rscript scripts/run_initial_test.R --year YYYY --pdf path/to/catalog.pdf")
}

year <- as.integer(argv$year)
pdf_path <- argv$pdf

if (!file.exists(pdf_path)) {
  stop(sprintf("PDF not found: %s", pdf_path))
}

dir_interim <- file.path("data", "interim", sprintf("year=%d", year))
dir_pages <- file.path(dir_interim, "pages")
dir_pdf_meta <- file.path(dir_interim, "pdf_metadata")
dir_processed <- file.path("data", "processed", sprintf("year=%d", year))

dir.create(dir_pages, recursive = TRUE, showWarnings = FALSE)
dir.create(dir_pdf_meta, recursive = TRUE, showWarnings = FALSE)
dir.create(dir_processed, recursive = TRUE, showWarnings = FALSE)

info <- pdftools::pdf_info(pdf_path)

manifest <- list(
  input_pdf = normalizePath(pdf_path, winslash = "/", mustWork = FALSE),
  year = year,
  num_pages = info$pages,
  pdf_version = info$pdf_version,
  encrypted = isTRUE(info$encrypted),
  created_at = as.character(Sys.time())
)

jsonlite::write_json(manifest, file.path(dir_interim, "manifest.json"), pretty = TRUE, auto_unbox = TRUE)

document_map <- list(
  year = year,
  pages = info$pages,
  sections = list(),
  notes = "Initial scaffold generated by run_initial_test.R"
)

jsonlite::write_json(document_map, file.path(dir_processed, "document_map.json"), pretty = TRUE, auto_unbox = TRUE)

cat(sprintf("Initialized pipeline structure for year=%d with %d pages.\n", year, info$pages))

